# Start with a base image containing Java runtime
FROM openjdk:8
# Add the application's jar to the container
ADD target/monitor-0.0.1-SNAPSHOT.jar monitor.jar
# Make port 8080 available to outside this container
EXPOSE 8080
# Run the jar file on command line
ENTRYPOINT ["java","-jar","monitor.jar"]